apps/glyph/views.py
from itertools import izip_longest
from apps.shared.models import db
from sqlalchemy import or_
from flask import Blueprint, request, render_template, redirect, url_for, g
from models import *
from forms import SearchForm
from pyelasticsearch import ElasticSearch

glyph = Blueprint(
    'glyph',
    __name__,
    template_folder='templates'
)

# initialise ElasticSearch
es = ElasticSearch('http://localhost:9200/')

@glyph.route('/', methods=['GET'])
def index():
    """ Records """
    search = SearchForm()
    return render_template('index.jinja', searchform=search)


@glyph.route(
    '/signs',
    methods=['GET'],
    defaults={'page': 1})
@glyph.route(
    '/signs/<int:page>',
    methods=['GET'])
def signs(page):
    search = SearchForm()
    q = Sign.query.order_by("sign_ref")
    page = q.paginate(page, per_page=25)
    return render_template('signs.jinja', page=page, searchform=search)


@glyph.route(
    '/cdp',
    methods=['GET'],
    defaults={'sign_id': 1})
@glyph.route(
    '/cdp/<int:sign_id>',
    methods=['GET'])
def cdp(sign_id):
    search = SearchForm()
    cdp_records = Cdp.query.filter_by(sign_id=sign_id).all()
    # pivot row results into columns. Yes, really.
    by_column = list(zip(
        cdp_records[0].columnitems.keys(), *[res.columnitems.values() for res in cdp_records]))
    # print flibble
    return render_template('cdp.jinja', cdp_records=cdp_records, row_cols=by_column, searchform=search)


@glyph.route(
    '/cdp/<int:sign_id>/images',
    methods=['GET'])
def sign_images(sign_id):
    search=SearchForm()
    sign = Sign.query.get(sign_id)
    return render_template('sign_images.jinja', sign=sign, searchform=search)


@glyph.route(
    '/tablet/<int:tablet_id>',
    methods=['GET'])
def tablet(tablet_id):
    search = SearchForm()
    tablet = Tablet.query.get_or_404(tablet_id)
    # split Signs into 12-item chunks
    # chunked = list(chunks(tablet.signs, 12))
    chunked = list(chunks(range(36), 12))
    return render_template('tablet.jinja', tablet=tablet, chunks=chunked, searchform=search)


@glyph.route(
    '/tablet/<int:tablet_id>/images',
    methods=['GET'])
def tablet_images(tablet_id):
    search=SearchForm()
    tablet = Tablet.query.get_or_404(tablet_id)
    return render_template('tablet_images.jinja', tablet=tablet, searchform=search)


@glyph.route(
    '/search',
    methods=['POST'])
def search():
    """ Search form """
    search = SearchForm()
    if search.validate_on_submit():
        return redirect(url_for('.search_results', query=search.search.data))
    else:
        return redirect(request.referrer)


@glyph.route('/search_results/<query>')
def search_results(query):
    q2 = {
        "size": 100,
        "query": {
            "fuzzy_like_this": {
                "fields": [
                    "sign.sign_ref",
                    "tablet.medium",
                    "tablet.city",
                    "tablet.period",
                    "tablet.sub_period",
                    "tablet.text_vehicle",
                    "tablet.method",
                    "tablet.genre",
                    "tablet.museum_number",
                    "tablet.ruler",
                    "tablet.notes",
                    "tablet.locality"
                ],
            "like_text": query,
            "max_query_terms": 10
            }
        }
    }
    res = es.search(q2, index='cdpp')
    # grab IDs from search results
    sign_ids = [r['_id'] for r in res['hits']['hits'] if r['_type'] == 'sign']
    tablet_ids = [r['_id'] for r in res['hits']['hits'] if r['_type'] == 'tablet']
    # retrieve DB records
    signs = []
    tablets = []
    if sign_ids:
        signs = db.session.query(Sign).filter(
            or_(*[Sign.id == id for id in sign_ids])
        ).all()
    if tablet_ids:
        tablets = db.session.query(Tablet).filter(
            or_(*[Tablet.id == id for id in tablet_ids])
        ).all()
    search=SearchForm()
    return render_template(
        'search_results.jinja',
        term=query,
        signs=signs,
        tablets=tablets,
        searchform=search)


@glyph.route(
    '/tablets',
    methods=['GET'],
    defaults={'page': 1})
@glyph.route(
    '/tablets/<int:page>',
    methods=['GET'])
def tablets(page):
    """
    Show result of restricting records using various criteria
    """
    search = SearchForm()
    q = Tablet.query.order_by('museum_number')
    if request.args.get("ruler"):
        q = Tablet.query.filter(
            Tablet.rulers.any(Ruler.name == request.args.get("ruler")))
    if request.args.get("medium"):
        q = q.join(Medium).filter(
            Medium.name == request.args.get("medium"))
    if request.args.get("script_type"):
        q = q.join(Script_Type).filter(
            Script_Type.script == request.args.get("script_type"))
    if request.args.get("city"):
        q = q.join(City, Tablet.city_id == City.id).filter(
            City.name == request.args.get("city"))
    if request.args.get("locality"):
        q = q.join(Locality).filter(
            Locality.area == request.args.get("locality"))
    if request.args.get("period"):
        q = q.join(Period).filter(
            Period.name == request.args.get("period"))
    if request.args.get("sub_period"):
        q = q.join(Sub_Period).filter(
            Sub_Period.name == request.args.get("sub_period"))
    if request.args.get("sent_from"):
        q = q.join(Correspondent, Tablet.from_id == Correspondent.id)\
            .filter(Correspondent.name == request.args.get("sent_from"))
    if request.args.get("sent_to"):
        q = q.join(Correspondent, Tablet.to_id == Correspondent.id)\
            .filter(Correspondent.name == request.args.get("sent_to"))
    if request.args.get("year"):
        q = q.join(Year).filter(
            Year.year == request.args.get("year"))
    if request.args.get("eponym"):
        q = q.join(Year).join(Eponym).filter(
            Eponym.name == request.args.get("eponym"))
    if request.args.get("text_vehicle"):
        q = q.join(Text_Vehicle).filter(
            Text_Vehicle.name == request.args.get("text_vehicle"))
    if request.args.get("language"):
        q = q.join(Language).filter(
            Language.name == request.args.get("language"))
    if request.args.get("method"):
        q = q.join(Method).filter(
            Method.name == request.args.get("method"))
    if request.args.get("genre"):
        q = q.join(Genre).filter(
            Genre.name == request.args.get("genre"))
    if request.args.get("function"):
        q = q.join(Function).filter(
            Function.name == request.args.get("function"))
    if request.args.get("dynasty"):
        q = q.join(Dynasty).filter(
            Dynasty.name == request.args.get("dynasty"))
    page = q.paginate(page, per_page=25)
    return render_template('tablets.jinja', page=page, searchform=search)


# utilities
def chunks(l, n):
    """ Yield successive n-sized chunks from l.
    """
    for i in xrange(0, len(l), n):
        yield l[i:i + n]

apps/glyph/templates/_utils.jinja
{% macro render_pagination(pagination, endpoint, request) %}
    <div>
        <ul class="pagination pagination-lg">
            {%- for page in pagination.iter_pages() %}
                {% if page %}
                    {% if page != pagination.page %}
                        <li><a href="{{ url_for(endpoint, page=page, **request.args) }}">{{ page }}</a></li>
                    {% else %}
                        <li class="active"><a href="#">{{ page }}</a></li>
                    {% endif %}
                    {% else %}
                        <li class="disabled"><a href="#">…</a></li>
                    {% endif %}
            {%- endfor %}
        </ul>
    </div>
{% endmacro %}

apps/glyph/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}CDP{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% assets "bootstrap" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
        {% endassets %}
        {% assets "bootstrap_theme" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
        {% endassets %}
        <!--[if lt IE 9]>
        {% assets "html5shim" %}
            <script src="{{ ASSET_URL }}"></script>
        {% endassets %}
        {% assets "respond" %}
            <script src="{{ ASSET_URL }}"></script>
        {% endassets %}
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% set navigation_bar = [
                    (url_for('glyph.index'), 'index', 'Home'),
                    (url_for('glyph.tablets'), 'tablets', 'Tablets'),
                    (url_for('glyph.signs'), 'signs', 'Signs')
                ] -%}
                {% set active_page = active_page|default('index') -%}
                <a class="navbar-brand" href="{{ url_for('glyph.index') }}">CDPP</a>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        {% for href, id, caption in navigation_bar %}
                            <li{% if id == active_page %} class="active"{% endif %}><a href="{{ href|e }}">{{ caption|e }}</a></li>
                        {% endfor %}
                        <li><form class="navbar-form navbar-left" role="search" method="POST" action="{{ url_for('glyph.search') }}">
                            {{ searchform.hidden_tag() }}
                            <div class="form-group">
                                {{ searchform.search(class_="form-control", placeholder="Sign / Tablet / Medium / Ruler / City etc.", size=40) }}
                            </div>
                            <button type="submit" class="btn btn-default">Search</button>
                        </form></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row-fluid">
                {% block side_container %}
                    <div class="col-md-4">
                        <div class="well">
                            {% block sidebar %}{% endblock %}
                        </div><!--/.well -->
                    </div><!--/span-->
                {% endblock %}
                <div class="col-md-8">
                    <div class="well">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
        {% assets "js_jquery" %}
            <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
            <script>window.jQuery || document.write('<script src="{{ ASSET_URL }}"><\/script>')</script>
        {% endassets %}
        {% assets "js_all" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}
    </body>

apps/glyph/templates/cdp.jinja
{% extends "base.jinja" %}
{% set active_page = "signs" %}
{% block title %}CDP records for sign {{ cdp_records[0].sign.sign_ref }}{% endblock %}
{% block content %}
<h3>CDPP Records </h3>
        <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr><td></td><td><strong>Entries</strong></td></tr>
        </thead>
        {%- for row in row_cols %}
            <tr>
            {%- for item in row %}
            {% if loop.index == 1 %}
                <td><strong>{{ item }}<strong></td>
            {% else %}
                <td>{{ item }}</td>
            {% endif %}
            {%- endfor %}
            </tr>
        {%- endfor %}
        </table>
{% endblock %}
{% block sidebar %}
<div class="container-fluid">
    <h3>Sign: {{ cdp_records[0].sign.sign_ref }} {%if cdp_records[0].sign.instances|length > 0 %}(<a href="{{ url_for('.sign_images', sign_id=cdp_records[0].sign.id) }}">images</a>){% endif %}</h3>
    <div class="row-fluid">
        <div class="span9">
        {%if cdp_records[0].sign.instances|length > 0 %}
            <h4>{{ cdp_records[0].sign.instances|length }} instances of this sign are known, ocurring in {{ cdp_records[0].sign.instances|groupby('tablet.museum_number')|length }} tablets:</h4>
                <ul class="list-group">
                {% for group in cdp_records[0].sign.instances|groupby('tablet.museum_number') %}
                    <li class="list-group-item"><strong><a href="{{ url_for(".tablet", tablet_id=group[1][0].tablet.id) }}">{{ group.grouper }} <span class="badge">{{group[1]|length}} {{'instances' if group[1]|length > 1 else 'instance' }}</span></a></strong></li>
                {% endfor %}
        {% else %}
            <h4>No Tablet records currently exist for this sign.
        {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

apps/glyph/templates/index.jinja
{% extends "base.jinja" %}
{% set active_page = "index" %}
{% from "_utils.jinja" import render_pagination %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="hero-unit">
        <h2>Welcome to the CDP Project</h2>
        <h3>Click <a href="{{ url_for('.tablets') }}">here</a> to see the tablets</h3>
        <h3>Click <a href="{{ url_for('.signs') }}">here</a> to see the signs</h3>
    </div>
{% endblock %}
{% block side_container %}
{% endblock %}

apps/glyph/templates/records.jinja
{% extends "base.jinja" %}
{% from "_utils.jinja" import render_pagination %}
{% block title %}Home{% endblock %}
{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Museum Number</th>
                    <th>Medium</th>
                    <th>Period</th>
                </tr>
            </thead>
            <tbody>
                {%- for item in page.items %}
                <tr>
                    <td><h4>{{ item.museum_number }}</h4></td>
                    <td>{{ item.medium.name }}</td>
                    <td>{{ item.period.name }}</td>
                </tr>
                {%- endfor %}
            </tbody>
        </table>
        {{ render_pagination(page, "records") }}
    </div>
{% endblock %}
{% block sidebar %}
{% for number in range(3) %}
    <li class="nav-header">Sidebar</li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
{% endfor %}
{% endblock %}

apps/glyph/templates/search_results.jinja
{% extends "base.jinja" %}
{% block title %}Search Results for {{ term }}{% endblock %}
{% block content %}
    <div class="container-fluid">
    {% if signs|length > 0 %}
        <h3>Signs</h3>
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Sign</th>
                    </tr>
                </thead>
                <tbody>
                    {%- for sign in signs %}
                    <tr>
                        <td><a href="{{ url_for(".cdp", sign_id=sign.id) }}"><h4>CDP Records for sign "{{ sign.sign_ref }}"</h4></a></td>
                    </tr>
                    {%- endfor %}
                </tbody>
            </table>
        {% endif %}
        {% if tablets|length > 0 %}
            <h3>Tablets</h3>
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Museum Number</th>
                        <th>Medium</th>
                        <th>Period</th>
                    </tr>
                </thead>
                <tbody>
                    {%- for tablet in tablets %}
                    <tr>
                        <td><a href="{{ url_for(".tablet", tablet_id=tablet.id) }}"><h4>{{ tablet.museum_number }}</h4></a></td>
                        <td>{{ tablet.medium.name }}</td>
                        <td>{{ tablet.period.name }}</td>
                    </tr>
                    {%- endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}
{% block sidebar %}
    {% set result_length = signs|length + tablets|length %}
    <h3>Search results for "{{ term }}"</h3>
    <h4>{{ result_length }} {{ 'results' if result_length > 1 or result_length == 0 else 'result' }} found</h4>
{% endblock %}

apps/glyph/templates/sign_images.jinja
{% extends "base.jinja" %}
{% set active_page = "signs" %}
{% from "_utils.jinja" import render_pagination %}
{% block title %}CDP: All images for {{ sign.sign_ref }}{% endblock %}
{% block content %}
    <div id="top" class="container-fluid">
        {% for group in sign.instances|groupby('tablet.museum_number') %}
            <div class="col-md-8">
                {% for instance in group[1] %}
                    {% if loop.first %}
                        <div class="row-fluid"><h4 id="{{ instance.tablet.museum_number }}">Tablet: <a title="Show '{{ instance.sign.sign_ref }}' instances in {{ instance.tablet.museum_number }}" href="{{ url_for('.tablet_images', tablet_id=instance.tablet.id) }}#{{ instance.sign.sign_ref }}">{{ instance.tablet.museum_number }}</a> <a href="#top" title="Back to top">&#10548;</a></h4></div>
                    {% endif %}
                    <div class="col-md-6">
                        <div class="thumbnail">
                            <a href="{{ url_for('static', filename='img/instance/%s.jpg' % instance.filename) }}" class="thumbnail">
                            <img src="{{ url_for('static', filename='img/instance/%s.jpg' % instance.filename) }}" alt="Example of {{ instance.sign.sign_ref }} in {{ instance.tablet.museum_number }}">
                            </a>
                            <div class="caption">
                                <ul class="list-group">
                                    <li class="list-group-item"><strong>Line:</strong> {{ instance.line.number }}</li>
                                    <li class="list-group-item"><strong>Function:</strong> {{ instance.function.name }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block sidebar %}
    <h3>Sign: <a href="{{ url_for('.cdp', sign_id=sign.id) }}">{{ sign.sign_ref }}</a></h3>
    <h4>{{ sign.instances|length }} {{ 'images' if sign.instances|length > 1 or sign.instances|length == 0 else 'image'}} are available for this sign, on {{ sign.instances|groupby('tablet.museum_number')|length }} tablets:</h4>
    <ul class="list-group">
        {% for group in sign.instances|groupby('tablet.museum_number') %}
            <li class="list-group-item"><strong><a href="{{ url_for(".tablet", tablet_id=group[1][0].tablet.id) }}">{{ group.grouper }} <span class="badge">{{group[1]|length}} {{'instances' if group[1]|length > 1 else 'instance' }}</span></a></strong> <a href="#{{ group.grouper }}" title="Jump to {{ group.grouper }} on this page">&#8680;</a></li>
        {% endfor %}
    </ul>
{% endblock %}

apps/glyph/templates/signs.jinja
{% extends "base.jinja" %}
{% set active_page = "signs" %}
{% from "_utils.jinja" import render_pagination %}
{% block title %}CDP: All Signs{% endblock %}
{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Sign</th>
                </tr>
            </thead>
            <tbody>
                {%- for item in page.items %}
                <tr>
                    <td><a href="{{ url_for(".cdp", sign_id=item.id) }}"><h4>CDP Records for sign "{{ item.sign_ref }}"</h4></a></td>
                </tr>
                {%- endfor %}
            </tbody>
        </table>
        {{ render_pagination(page, ".signs", request) }}
    </div>
{% endblock %}

apps/glyph/templates/tablet.jinja
{% extends "base.jinja" %}
{% set active_page = "tablets" %}
{% block title %}Individual Tablet View for {{ tablet.museum_number }}{% endblock %}
{% block content %}
<div class="row-fluid">
        <h3>{{ '%s sign instances are ' % tablet.instances|length if tablet.instances|length > 1 else '%s sign instance is ' % tablet.instances|length }} available for this tablet ({{ tablet.instances|groupby('sign.sign_ref')|length }} {{ 'signs' if tablet.instances|groupby('sign.sign_ref')|length  > 1 else 'sign'}}):</h3>
        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
        <th>Sign</th>
        <th>Surface</th>
        <th>Column</th>
        <th>Line</th>
        <th>Function</th>
        <th>Iteration</th>
        <th>JJT Notes 2012</th>
        <th>Notes</th>
        <th>Language</th>
        </tr>
        </thead>
        <tbody>
            {%- for instance in tablet.instances|sort(attribute='sign.sign_ref') %}
            <tr>
            <td><strong><a href="{{ url_for(".cdp", sign_id=instance.sign_id) }}">{{ instance.sign.sign_ref }}</a></strong></td>
                <td>{{ instance.surface.name }}</td>
                <td>{{ instance.column.number }}</td>
                <td>{{ instance.line.number }}</td>
                <td>{{ instance.function.name }}</td>
                <td>{{ instance.iteration.number }}</td>
                <td>{{ instance.jjt_notes }}</td>
                <td>{{ instance.notes }}</td>
                <td>{{ instance.languages|join(", ", attribute='name') }}</td>
            </tr>
            {%- endfor %}
            </tbody>
        </table>
</div>
{% endblock %}
{% block sidebar %}
    <h3>Tablet: {{ tablet.museum_number }} (<a href="{{ url_for('.tablet_images', tablet_id=tablet.id) }}">images</a>)</h3>
    <ul class="list-group">
        {% if tablet.rulers %}
        <li class="list-group-item"><strong>{{ 'Rulers' if tablet.rulers|length > 1 else 'Ruler' }}:</strong>
        <ul>
        {% for ruler in tablet.rulers %}
            <li><a href="{{ url_for('.tablets', ruler=ruler.name, page=1) }}">{{ ruler.name }}</a></li>
        {% endfor %}
        </ul>
        </li>
        {% endif %}
        {% if tablet.medium %}
            <li class="list-group-item"><strong>Medium:</strong> <a href="{{ url_for('.tablets', medium=tablet.medium.name) }}">{{ tablet.medium.name }}</a></li>
        {% endif %}
        {% if tablet.script_type %}
            <li class="list-group-item"><strong>Script Type:</strong> <a href="{{ url_for('.tablets', script_type=tablet.script_type.script) }}">{{ tablet.script_type.script }}</a></li>
        {% endif %}
        {% if tablet.locality %}
            <li class="list-group-item"><strong>Locality:</strong> <a href="{{ url_for('.tablets', locality=tablet.locality.area) }}">{{ tablet.locality.area }}</a></li>
        {% endif %}
        {% if tablet.city %}
            <li class="list-group-item"><strong>City:</strong> <a href="{{ url_for('.tablets', city=tablet.city.name) }}">{{ tablet.city.name }}</a></li>
        {% endif %}
        {% if tablet.publication %}
            <li class="list-group-item"><strong>Publication:</strong> {{ tablet.publication }}</li>
        {% endif %}
        {% if tablet.year %}
            <li class="list-group-item">
                <strong>Year:</strong> <a href="{{ url_for('.tablets', year=tablet.year.year) }}">{{ tablet.year.year }}</a>
                {% if tablet.year.eponym %}
                    (Eponym: <a href="{{ url_for('.tablets', eponym=tablet.year.eponym.name) }}">{{ tablet.year.eponym.name }}</a>)
                {% endif %}
            </li>
        {% endif %}
        {% if tablet.period %}
            <li class="list-group-item"><strong>Period:</strong> <a href="{{ url_for('.tablets', period=tablet.period.name) }}">{{ tablet.period.name }}</a></li>
        {% endif %}
        {% if tablet.sub_period %}
            <li class="list-group-item"><strong>Sub-Period:</strong> <a href="{{ url_for('.tablets', sub_period=tablet.sub_period.name) }}">{{ tablet.sub_period.name }}</a></li>
        {% endif %}
        {% if tablet.dynasty %}
            <li class="list-group-item"><strong>Dynasty:</strong> <a href="{{ url_for('.tablets', dynasty=tablet.dynasty.name) }}">{{ tablet.dynasty.name }}</a></li>
        {% endif %}
        {% if tablet.sent_from %}
            <li class="list-group-item"><strong>Sent From:</strong> <a href="{{ url_for('.tablets', sent_from=tablet.sent_from.name) }}">{{ tablet.sent_from.name }}</a></li>
        {% endif %}
        {% if tablet.sent_to %}
            <li class="list-group-item"><strong>Sent To:</strong> <a href="{{ url_for('.tablets', sent_to=tablet.sent_to.name) }}">{{ tablet.sent_to.name }}</a></li>
        {% endif %}
        {% if tablet.text_vehicle %}
            <li class="list-group-item"><strong>Text Vehicle:</strong> <a href="{{ url_for('.tablets', text_vehicle=tablet.text_vehicle.name) }}">{{ tablet.text_vehicle.name }}</a></li>
        {% endif %}
        {% if tablet.language %}
            <li class="list-group-item"><strong>Language:</strong> <a href="{{ url_for('.tablets', language=tablet.language.name) }}">{{ tablet.language.name }}</a></li>
        {% endif %}
        {% if tablet.method %}
            <li class="list-group-item"><strong>Method:</strong> <a href="{{ url_for('.tablets', method=tablet.method.name) }}">{{ tablet.method.name }}</a></li>
        {% endif %}
        {% if tablet.genre %}
            <li class="list-group-item"><strong>Genre:</strong> <a href="{{ url_for('.tablets', genre=tablet.genre.name) }}">{{ tablet.genre.name }}</a></li>
        {% endif %}
        {% if tablet.function %}
            <li class="list-group-item"><strong>Function:</strong> <a href="{{ url_for('.tablets', function=tablet.function.name) }}">{{ tablet.function.name }}</a></li>
        {% endif %}
        {% if tablet.notes %}
            <li class="list-group-item"><strong>Notes:</strong> {{ tablet.notes }}</li>
        {% endif %}
        {% if tablet.author %}
            <li class="list-group-item"><strong>Scribe:</strong> {{ tablet.author.name }}</li>
        {% endif %}
    </ul>
    <h3>Random images of {{ tablet.museum_number }}</h3>
    {% for n in range(4) %}
        {% set image = tablet.instances|random %}
    <!-- for-each loop goes here, because we've joined to Signs on Museum Number -->
        <div class="row-fluid">
            <div class="thumbnail">
                <a href="{{ url_for('static', filename='img/instance/%s.jpg' % image.filename) }}" class="thumbnail">
                    <img src="{{ url_for('static', filename='img/instance/%s.jpg' % image.filename) }}" alt="Example of {{ image.sign.sign_ref }} in {{ tablet.museum_number }}">
                </a>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Sign:</strong> <a title="Show the {{ tablet.museum_number }} instance of '{{ image.sign.sign_ref }}'" href="{{  url_for('.sign_images', sign_id=image.sign.id) }}#{{ tablet.museum_number }}">{{ image.sign.sign_ref }}</a></li>
                        <li class="list-group-item"><strong>Line:</strong> {{ image.line.number }}</li>
                        <li class="list-group-item"><strong>Function:</strong> {{ image.function.name }}</li>
                    </ul>
            </div>
        </div>
    {% endfor %}
{% endblock %}

apps/glyph/templates/tablets.jinja
{% extends "base.jinja" %}
{% set active_page = "tablets" %}
{% from "_utils.jinja" import render_pagination %}
{% block title %}CDP: Tablets By Category{% endblock %}
{% block content %}
    <div class="container-fluid">
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Museum Number</th>
                    <th>Medium</th>
                    <th>Period</th>
                </tr>
            </thead>
            <tbody>
                {%- for item in page.items %}
                <tr>
                    <td><a href="{{ url_for(".tablet", tablet_id=item.id) }}"><h4>{{ item.museum_number }}</h4></a></td>
                    <td>{{ item.medium.name }}</td>
                    <td>{{ item.period.name }}</td>
                </tr>
                {%- endfor %}
            </tbody>
        </table>
        {{ render_pagination(page, ".tablets", request) }}
    </div>
{% endblock %}